### ISSUE TITLE
"Clean Start" setting in UI does not import <clean-start> setting from XML config file

### ISSUE THREAD

**Issue by calliday** [hivemq/hivemq-edge#284] opened 2024-02-08 17:14 UTC
## Context
This issue is regarding the Web UI for configuring a bridge.

## Expected behavior
The "Clean Start" setting in the bridge configuration UI should import the `<clean-start>` setting from the XML config file.

## Actual behavior
The UI for bridge configuration doesn't import the <clean-start> setting within the XML config file. The consequence is that if a user edits the bridge and saves it, without navigating to the "Broker Configuration" page to uncheck the "Clean Start" setting, the `<clean-start>` setting will always be configured to `true` in the XML config file.

<img width="1744" alt="Screenshot 2024-02-05 at 1 31 24 PM" src="https://github.com/hivemq/hivemq-edge/assets/43559869/8ca104d1-ff64-4713-8fe5-f59a5ecf7a1f">

### Steps

- Update a bridge "Broker Configuration" to have "Clean Start" unchecked.
- Save. 
- Check the XML config file to see the `<clean-start>` setting reflected.
- Update the bridge without touching the "Clean Start" setting.
- Check the XML config file to see that `<clean-start>` has been set to `true`.

## Details

- Affected HiveMQ Edge version(s): 2023.9

**Comment by DC2-DanielKrueger** [comment] 2024-04-08 11:36
Thank you for raising the issue, 

I can reproduce the issue. The root cause is within the front end as the backend response for the bridge information contains  cleanStart=false correctly. 

Best regards
Daniel

**Comment by DC2-DanielKrueger** [comment] 2024-04-11 08:58
The problem was fixed. Thank you again for bringing it up @calliday. The fix will be part of the next release. [PR](https://github.com/hivemq/hivemq-edge/pull/359)

Best regards, 
Daniel

**Closed by DC2-DanielKrueger** 2024-04-11 08:58 UTC
Labels: tracked
